name: default
train:
    batch_size: 64
    LOAD_EPOCH:
    epochs: 100
    num_workers: 6
    eval_period: 1
    checkpoint_period: 2
    device: cuda
    lr: 0.001
model:
    hidden_size: 1024
    embedding_sizeT: 512
    embedding_sizeN: 300
    dropout: 0.1
    num_layers: 1
    label_smoothing: 0
    pointer: True
data:
    truncate_size: 100
    N_filename: ./pickle_data/PY_non_terminal_small.pickle
    T_filename: ./pickle_data/PY_terminal_10k_whole.pickle
    