name: default
train:
    batch_size: 12
    LOAD_EPOCH:
    epochs: 1000
    num_workers: 6
    eval_period: 1
    checkpoint_period: 2
    device: cuda
    lr: 0.001
model:
    hidden_size: 512
    embedding_sizeT: 512
    embedding_sizeN: 300
    dropout: 0.1
    num_layers: 1 # more is not supported
    label_smoothing: 0 # >0 produce negative loss (might be bug here)
    pointer: True
data:
    truncate_size: 150
    N_filename: ./pickle_data/PY_non_terminal_small.pickle
    T_filename: ./pickle_data/PY_terminal_10k_whole.pickle
    